test-*-verifies-pinned-cert: reshape per the kind of common scheme: re-use the method setup
As in other tests of this kind now, we let the common setup code to
set up the repo and servers and apt config for a specific quasi-method
(in this case: with pinning), and then the scheme is to run apt with
the crucial part of the config undone, make sure apt fails, and then
see that it works with the config restored: this is a proof that this
part of config actually affects apt in a way we wish.

As a future re-organization in a move to reduce the number of tests
run and the excessive meaningless method modifiers, we can make such
tests modify the current method with a modifier corresponding to the
tested feature and do such a setup just for this test, without
meaninglessly running a lot of tests with such modified method.

For instance, it's similar to:

diff test-apt-method-http-connects-to-nonlocalhost test-apt-method-https-verifies-pinned-cert

diff --git a/test/integration/test-apt-method-https-verifies-pinned-cert b/test/integration/test-apt-method-https-verifies-pinned-cert
--- a/test/integration/test-apt-method-https-verifies-pinned-cert
+++ b/test/integration/test-apt-method-https-verifies-pinned-cert
@@ -4,17 +4,22 @@ set -eu
 TESTDIR=$(readlink -f $(dirname $0))
 
 case "$APT_TEST_METHOD" in
-	https|https_*)
+	https*_pinned*)
 		:
 		;;
 	*)
-		echo 'SKIP (makes sense only for APT_TEST_METHOD being https*)' >&2
+		echo 'SKIP (we rely on APT_TEST_METHOD being https*_pinned* for the cert setup)' >&2
 		exit 0
 		;;
 esac
 
-. $TESTDIR/framework-without-repo
-prereq $TESTDIR/test-apt-install-simple
+. $TESTDIR/framework
+
+setupenvironment
+
+buildpackage 'simple-package'
+
+generaterepository_and_switch_sources "$TMPWORKINGDIRECTORY/usr/src/RPM/RPMS"
 
 # Generate another key, and pin apt to it. Check cert pinning
 
@@ -23,23 +28,32 @@ mk_intermediate cert/"${0##*/}"@"$NGINX_HOST"/crt \
 		ssl_keygen
 
 msgmsg 'Pinning invalid cert in apt'
+# save current conf
+readonly APT_TEST_PINNING_CONF_SAVED=$TMPWORKINGDIRECTORY/apt-pinning.conf
+rm -f "$APT_TEST_PINNING_CONF_SAVED"
+if [ -e "$APT_TEST_PINNING_CONF" ]; then
+   mv "$APT_TEST_PINNING_CONF" -T "$APT_TEST_PINNING_CONF_SAVED"
+fi
+
 cat >| "$APT_TEST_PINNING_CONF" <<- END
 Acquire::https::PinnedCert	"$APT_TEST_INTERMEDIATES/cert/${0##*/}@$NGINX_HOST/crt";
 END
 
 testfailure aptget update
 
-testpkgnotinstalled 'conflicting-package-one'
-testfailure aptget install conflicting-package-one
-testpkgnotinstalled 'conflicting-package-one'
+testpkgnotinstalled 'simple-package'
+testfailure aptget install 'simple-package'
+testpkgnotinstalled 'simple-package'
 
-msgmsg 'Pinning the valid cert in apt'
-cat >| "$APT_TEST_PINNING_CONF" <<- END
-Acquire::https::PinnedCert	"$NGINX_CRT";
-END
+msgmsg 'Restoring the pinning conf for apt (with the presumably valid cert)'
+# clean up (restore the conf)
+rm "$APT_TEST_PINNING_CONF"
+if [ -e "$APT_TEST_PINNING_CONF_SAVED" ]; then
+   mv "$APT_TEST_PINNING_CONF_SAVED" -T "$APT_TEST_PINNING_CONF"
+fi
 
 testsuccess aptget update
 
-testpkgnotinstalled 'conflicting-package-one'
-testsuccess aptget install conflicting-package-one
-testpkginstalled 'conflicting-package-one'
+testpkgnotinstalled 'simple-package'
+testsuccess aptget install 'simple-package'
+testpkginstalled 'simple-package'
